services:

  postgres:
    image: postgres:16
    container_name: agenda-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql


  app:
    build: .
    container_name: agenda-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: agenda
      DB_PORT: 5432
    depends_on:
      - postgres


volumes:
  postgres_data: